export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILED = 'FETCH_NOTIFICATIONS_FAILED';

export const UPDATE_NOTIFICATIONS_REAL_TIME = 'UPDATE_NOTIFICATIONS_REAL_TIME';

export const MARK_NOTIFICATION_SEEN = 'MARK_NOTIFICATION_SEEN';
export const MARK_NOTIFICATION_SEEN_SUCCESS = 'MARK_NOTIFICATION_SEEN_SUCCESS';
export const MARK_NOTIFICATION_SEEN_FAILED = 'MARK_NOTIFICATION_SEEN_FAILED';
