export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAIELD';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_EMAIL_SUCCESS = 'CHANGE_EMAIL_SUCCESS';
export const CHANGE_EMAIL_FAILED = 'CHANGE_EMAIL_FAILED';

export const CONFIRM_EMAIL_CHANGE = 'CONFIRM_EMAIL_CHANGE';
export const CONFIRM_EMAIL_CHANGE_SUCCESS = 'CONFIRM_EMAIL_CHANGE_SUCCESS';
export const CONFIRM_EMAIL_CHANGE_FAILED = 'CONFIRM_EMAIL_CHANGE_FAILED';

export const FETCH_PROFILE_INFOS = 'FETCH_PROFILE_INFOS';
export const FETCH_PROFILE_INFOS_SUCCESS = 'FETCH_PROFILE_INFOS_SUCCESS';
export const FETCH_PROFILE_INFOS_FAILED = 'FETCH_PROFILE_INFOS_FAILED';
