version: "3.8"
services:
  administration:
    image: pfe/frontend:1.0
    ports:
      - "5000:5000"
    restart: on-failure
    networks:
      - frontend

  backend-api:
    image: pfe/backend:1.0
    ports:
      - "8888:8888"
    restart: on-failure
    depends_on:
      - postgres-db
    environment:
      PG_HOSTNAME: postgres-db
    volumes:
      - ../backend/backend:/opt/backend
    networks:
      - backend
  
  face-detection-api:
    image: pfe:/face_detection:1.0
    restart: on-failure
    ports:
      - "8787:8787"
    volumes:
      - ../face_detection:/app
    networks:
      - backend

  postgres-db:
    image: postgres:14.1
    environment:
      POSTGRES_DB: surv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_lib:/var/lib/postgresql/data
    networks:
      - backend
    restart: on-failure
  
  redis:
    image: redis:7.0.0
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: on-failure

  pfe-gateway:
    image: haproxy:alpine
    ports:
      - 80:80
    depends_on:
      - administration
      - backend-api
    networks:
      - backend
      - frontend
    restart: on-failure
    volumes:
      - ./proxy-config/config.cfg:/usr/local/etc/haproxy/haproxy.cfg

volumes:
  pg_lib:

networks:
  frontend:
  backend:
