export const FETCH_CLUSTERS = 'FETCH_CLUSTERS';
export const FETCH_CLUSTERS_SUCCESS = 'FETCH_CLUSTERS_SUCCESS';
export const FETCH_CLUSTERS_FAILED = 'FETCH_CLUSTERS_FAILED';

export const CREATE_CLUSTER = 'CREATE_CLUSTER';
export const CREATE_CLUSTER_SUCCESS = 'CREATE_CLUSTER_SUCCESS';
export const CREATE_CLUSTER_FAILED = 'CREATE_CLUSTER_FAILED';

export const UPDATE_CLUSTER = 'UPDATE_CLUSTER';
export const UPDATE_CLUSTER_SUCCESS = 'UPDATE_CLUSTER_SUCCESS';
export const UPDATE_CLUSTER_FAILED = 'UPDATE_CLUSTER_FAILED';

export const DELETE_CLUSTER = 'DELETE_CLUSTER';
export const DELETE_CLUSTER_SUCCESS = 'DELETE_CLUSTER_SUCCESS';
export const DELETE_CLUSTER_FAILED = 'DELETE_CLUSTER_FAILED';
